apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-python-app
  namespace: argocd
spec:
  project: my-project
  source:
    repoURL: https://github.com/elpadev/argo-cd-application-template
    targetRevision: feature/add-application-project-cr
    path: deploy/helm/my-python-app
    helm:
      releaseName: my-python-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
